#!/usr/bin/env bash
# Configuring Nginx so that its HTTP response contains a custom header (on web-01 and web-02)

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "48i\\\tadd_header X-Served-By \"$HOSTNAME"\;\n" /etc/nginx/sites-available/default
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo service nginx start