#!/usr/bin/env bash
# this is a script that pings an IP address passed as an argument (acts like ping)
if [ "$#" -lt "1" ]
then
    echo "usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping "$1" -c 5
fi