#!/usr/bin/env bash
# bash script that displays the content of the /etc/passwd file (only the username,user id and home directory)
FILE="/etc/passwd"
while read -r line
do
echo "$line" | cut -d ":" -f1,3,6
done < $FILE