#!/usr/bin/env bash
# Bash script that displays "Best School" 10 times, & for the 9th iteration,displays "Best School" then "Hi" 
j=0
while [ $j -lt 10 ]
do
    if [ $j -eq 8 ]
    then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
j=$((j+1))
done