#!/usr/bin/env bash
# bash script that displays numbers from 1-20 then displays 4 and then bad luck from China for the 4th loop iteration displays 9 and then bad luck from Japan for the 9th loop iteration displays 17 and then bad luck from Italy for the 17th loop iteration
j=1
while [ $j -le 20 ]
do
    case $j in
        "4")
            echo $j
            echo "bad luck from China";;
        "9")
            echo $j
            echo "bad luck from Japan";;
        "17")
            echo $j
            echo "bad luck from Italy";;
        *)
            echo $j;;
    esac
    ((j++))
done