#!/usr/bin/env bash
# Bash script that displays the current directory in a list format where only te name after the firts dash is displayed
for file in *
do
        if [ -f "$file" ]
        then
                echo "$file" | cut -d "-" -f2
        fi
done