#!/usr/bin/env bash
# this script configures an ubuntu server with 1; localhost resolves to 127.0.0.2 (2; facebook.com resovels to 8.8.8.8
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sed -i '2i8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts